[BE] ♻️ refactor: 구문 변경

diff --git a/Jenkinsfile.eureka b/Jenkinsfile.eureka
--- a/Jenkinsfile.eureka
+++ b/Jenkinsfile.eureka
@@ -43,20 +43,22 @@ pipeline {
 	    }
 
         // 백엔드 빌드 단계
-        try{
-            stage('BE-Build') {
+        stage('BE-Build') {
             steps {
-                dir("./Server/eureka") {
-                    // Gradle 빌드 실행
-                    sh 'chmod +x ./gradlew'
-                    sh './gradlew clean build'
+                script {
+                    try {
+                        dir("./Server/eureka") {
+                            // Gradle 빌드 실행
+                            sh 'chmod +x ./gradlew'
+                            sh './gradlew clean build'
+                        }
+                    } catch (Exception e) {
+                        echo 'Build failed. Checking logs...'
+                        sh 'cat ./Server/eureka/build/reports/tests/test/index.html || true'
+                        throw e
+                    }
                 }
             }
-        }
-        } catch (Exception e) {
-        echo 'Build failed. Checking logs...'
-        sh 'cat ./Server/eureka/build/reports/tests/test/index.html'
-        throw e
         }
         
 
